// The shared font set: one registry, one loader, one text-to-contours path for
// every generator that puts type on a model.
//
// Offline bundles: the .ttf files are referenced through `import.meta.glob` as
// asset URLs, so each app's own `vite build` emits its own copy into its own
// dist/. Sharing the source here dedupes the repo without coupling the outputs —
// shipping one generator offline is still a straight copy of its dist/.
/// <reference path="./declarations.d.ts" />
import * as opentype from 'opentype.js';

export { FONTS, type FontChoice } from './registry';
export * from './textLayout';
// The symbol library: every solid glyph inside icon-fallback.ttf, with names,
// categories and search terms. Generated by scripts/fetch-icons.mjs.
export { ICONS, ICON_CATEGORIES, searchIcons, iconById, iconByChar, type IconChoice, type IconCategory } from './icons';
// The same library arranged for a person: a hand-picked Popular set and a dozen named
// groups over the raw categories. Shared so every symbol picker opens on the same page.
export { POPULAR_IDS, POPULAR, QUICK_PICKS, SYMBOL_GROUPS, searchGroup, type SymbolGroup } from './symbolGroups';

import { FONTS, type FontChoice } from './registry';
import { requirementOf, SCRIPTS } from './coverage';
// What a face covers and what a string needs, measured on the same character sets.
export { UNCOVERED } from './coverage';

/** CSS font-family prefix for the @font-face rules in `@vostok/fonts/fonts.css`.
 *  Used for HTML previews only — the 3D geometry comes from opentype. */
export const FONT_FAMILY_PREFIX = 'VL-';

/** The CSS family name to preview `fontId` with. */
export const fontFamilyFor = (fontId: string): string => `${FONT_FAMILY_PREFIX}${fontId}`;


// Vite resolves this glob relative to THIS file, so it works from any app that
// consumes the package as source. `import: 'default'` yields URLs, not bytes —
// the fonts stay out of the JS bundle and are fetched only when used.
const fontUrls = (import.meta as any).glob('./fonts/*.ttf', {
  eager: true,
  import: 'default',
}) as Record<string, string>;

const fontUrlById: Record<string, string> = Object.entries(fontUrls).reduce(
  (acc, [path, url]) => {
    acc[path.replace('./fonts/', '').replace('.ttf', '')] = url;
    return acc;
  },
  {} as Record<string, string>,
);

/** Get the URL for a given font ID so the app can inject its own @font-face or use it directly. */
export const getFontUrl = (fontId: string): string | undefined => fontUrlById[fontId];

/** Fonts imported by the user at runtime, parsed and held in memory. */
const customFonts = new Map<string, any>();
const fontCache = new Map<string, any>();

/** Parse a .ttf/.otf the user supplied. Kept here so apps never need to depend
 *  on opentype directly — the package owns the one copy. */
export function parseFont(buffer: ArrayBuffer): any {
  return opentype.parse(buffer);
}

/** Register a font the user imported from a .ttf/.otf, so `getFont` can find it. */
export function registerCustomFont(fontId: string, parsed: any): void {
  customFonts.set(fontId, parsed);
  fontCache.set(fontId, parsed);
}

async function loadFont(fontId: string): Promise<any> {
  const custom = customFonts.get(fontId);
  if (custom) return custom;
  const url = fontUrlById[fontId];
  if (!url) {
    if (fontId.startsWith('custom-')) {
      throw new Error('Custom font is missing. Please import the .ttf/.otf file again.');
    }
    throw new Error(`Font url not resolved for ${fontId}`);
  }
  const r = await fetch(url);
  if (!r.ok) throw new Error(`Fetch failed for font ${fontId}`);
  return opentype.parse(await r.arrayBuffer());
}

/** Parsed opentype font for `fontId`, cached for the session. */
export async function getFont(fontId: string): Promise<any> {
  let f = fontCache.get(fontId);
  if (!f) {
    f = await loadFont(fontId);
    fontCache.set(fontId, f);
  }
  return f;
}

/** Fonts shown as instant cards; the rest live behind "Browse all fonts". */
export const curatedFonts = (): FontChoice[] => FONTS.filter((f) => f.curated);

/**
 * What a string needs from a font, so a face that would draw "?" or an empty box is flagged
 * before it does. One entry per kind of character the text holds, each a name a face lists in
 * `subsets` (`cyrillic`, `korean`, `kana`, `japanese`...), or two joined by `|` when either will
 * do: a Han character in both the Japanese and the Chinese set needs
 * `japanese|chinese-simplified`. `UNCOVERED` stands for a character no bundled face has: a CJK
 * one past the common set the files are cut to, or Hangul typed as separate jamo. Basic Latin,
 * Latin-1 and punctuation need nothing.
 */
export function getRequiredSubsets(text: string): string[] {
  const needs = new Set<string>();
  for (const char of text) {
    const need = requirementOf(char.codePointAt(0)!);
    if (need) needs.add(need);
  }
  return Array.from(needs);
}

/** Every letter and digit of `text` is in this parsed font's cmap. */
function cmapCovers(parsed: any, text: string): boolean {
  const map: Record<number, number> | undefined = parsed?.tables?.cmap?.glyphIndexMap;
  if (!map) return true;
  for (const char of text) {
    if (/[\p{L}\p{N}]/u.test(char) && !map[char.codePointAt(0)!]) return false;
  }
  return true;
}

/** Whether `font` has every character in `text`. A bundled face answers from the coverage its
 *  file was measured to have; a font the user imported, from its own cmap, letter by letter. */
export function isFontSupported(font: FontChoice, text: string): boolean {
  const imported = customFonts.get(font.id);
  if (imported) return cmapCovers(imported, text);
  if (!font.subsets) return true;
  return getRequiredSubsets(text).every((need) => need.split('|').some((name) => font.subsets.includes(name)));
}

/** The alphabets `font` writes, for a person to filter by: any of 'Latin', 'Cyrillic', 'Greek',
 *  'Korean', 'Japanese', 'Chinese', always in that order. A face with kana and no kanji counts
 *  as Japanese; a kanji typed in it is still flagged. */
export function fontScripts(font: FontChoice): string[] {
  return SCRIPTS.filter(([, names]) => names.some((name) => font.subsets?.includes(name))).map(([script]) => script);
}

/** The icon fallback font, used when a glyph is missing from the chosen face. */
export const FALLBACK_FONT_ID = 'icon-fallback';

// A font the user brings: one import path for every generator (see import.ts).
export { importFontBuffer, importFontFiles, toPickerFont, fontSupportsText, type ImportedFonts } from './import';
