// AUTO-GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.
export interface FontChoice { id: string; label: string; category: string; curated: boolean; subsets: string[]; }
export const FONTS: FontChoice[] = [
  {
    "id": "abril-fatface",
    "label": "Abril Fatface",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "aldrich",
    "label": "Aldrich",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "alex-brush",
    "label": "Alex Brush",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "alfa-slab-one",
    "label": "Alfa Slab One",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "allura",
    "label": "Allura",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "amatic-sc",
    "label": "Amatic SC",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "cyrillic",
      "hebrew",
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "anton",
    "label": "Anton",
    "category": "Clean",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "architects-daughter",
    "label": "Architects Daughter",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "archivo-black",
    "label": "Archivo Black",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "arvo",
    "label": "Arvo",
    "category": "Slab",
    "curated": true,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "audiowide",
    "label": "Audiowide",
    "category": "Tech",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "bakbak-one",
    "label": "Bakbak One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "devanagari",
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "baloo-2",
    "label": "Baloo 2",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "devanagari",
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "bangers",
    "label": "Bangers",
    "category": "Comic",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "barlow-condensed",
    "label": "Barlow Condensed",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "bebas-neue",
    "label": "Bebas Neue",
    "category": "Clean",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "bevan",
    "label": "Bevan",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "bitter",
    "label": "Bitter",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "black-han-sans",
    "label": "Black Han Sans",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "korean",
      "latin"
    ]
  },
  {
    "id": "black-ops-one",
    "label": "Black Ops One",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "boogaloo",
    "label": "Boogaloo",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "bowlby-one",
    "label": "Bowlby One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "bowlby-one-sc",
    "label": "Bowlby One SC",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "bree-serif",
    "label": "Bree Serif",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "bungee",
    "label": "Bungee",
    "category": "Display",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "butcherman",
    "label": "Butcherman",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "caveat",
    "label": "Caveat",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "chakra-petch",
    "label": "Chakra Petch",
    "category": "Tech",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext",
      "thai",
      "vietnamese"
    ]
  },
  {
    "id": "changa-one",
    "label": "Changa One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "chewy",
    "label": "Chewy",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "cinzel",
    "label": "Cinzel",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "cinzel-decorative",
    "label": "Cinzel Decorative",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "comfortaa",
    "label": "Comfortaa",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "greek",
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "coming-soon",
    "label": "Coming Soon",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "concert-one",
    "label": "Concert One",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "cookie",
    "label": "Cookie",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "courgette",
    "label": "Courgette",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "creepster",
    "label": "Creepster",
    "category": "Spooky",
    "curated": true,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "crete-round",
    "label": "Crete Round",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "cutive-mono",
    "label": "Cutive Mono",
    "category": "Mono",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "damion",
    "label": "Damion",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "dancing-script",
    "label": "Dancing Script",
    "category": "Script",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "do-hyeon",
    "label": "Do Hyeon",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "korean",
      "latin"
    ]
  },
  {
    "id": "domine",
    "label": "Domine",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "dotgothic16",
    "label": "DotGothic16",
    "category": "Pixel",
    "curated": false,
    "subsets": [
      "cyrillic",
      "japanese",
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "eater",
    "label": "Eater",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "electrolize",
    "label": "Electrolize",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "ewert",
    "label": "Ewert",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "faster-one",
    "label": "Faster One",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "fjalla-one",
    "label": "Fjalla One",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "fredoka",
    "label": "Fredoka",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "hebrew",
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "frijole",
    "label": "Frijole",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "fugaz-one",
    "label": "Fugaz One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "gaegu",
    "label": "Gaegu",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "korean",
      "latin"
    ]
  },
  {
    "id": "gloria-hallelujah",
    "label": "Gloria Hallelujah",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "gochi-hand",
    "label": "Gochi Hand",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "grandstander",
    "label": "Grandstander",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "great-vibes",
    "label": "Great Vibes",
    "category": "Script",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "greek-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "griffy",
    "label": "Griffy",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "gruppo",
    "label": "Gruppo",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "handjet",
    "label": "Handjet",
    "category": "Pixel",
    "curated": false,
    "subsets": [
      "arabic",
      "armenian",
      "cyrillic",
      "cyrillic-ext",
      "greek",
      "hebrew",
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "handlee",
    "label": "Handlee",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "henny-penny",
    "label": "Henny Penny",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "iceland",
    "label": "Iceland",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "indie-flower",
    "label": "Indie Flower",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "jolly-lodger",
    "label": "Jolly Lodger",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "josefin-sans",
    "label": "Josefin Sans",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "josefin-slab",
    "label": "Josefin Slab",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "jua",
    "label": "Jua",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "korean",
      "latin"
    ]
  },
  {
    "id": "jura",
    "label": "Jura",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "greek",
      "greek-ext",
      "kayah-li",
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "kalam",
    "label": "Kalam",
    "category": "Handwriting",
    "curated": true,
    "subsets": [
      "devanagari",
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "kanit",
    "label": "Kanit",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "thai",
      "vietnamese"
    ]
  },
  {
    "id": "kaushan-script",
    "label": "Kaushan Script",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "lilita-one",
    "label": "Lilita One",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "lobster",
    "label": "Lobster",
    "category": "Script",
    "curated": true,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "lora",
    "label": "Lora",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "math",
      "symbols",
      "vietnamese"
    ]
  },
  {
    "id": "luckiest-guy",
    "label": "Luckiest Guy",
    "category": "Comic",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "major-mono-display",
    "label": "Major Mono Display",
    "category": "Mono",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "marcellus",
    "label": "Marcellus",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "marck-script",
    "label": "Marck Script",
    "category": "Script",
    "curated": false,
    "subsets": [
      "cyrillic",
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "metal-mania",
    "label": "Metal Mania",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "michroma",
    "label": "Michroma",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "modak",
    "label": "Modak",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "devanagari",
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "monoton",
    "label": "Monoton",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "montserrat",
    "label": "Montserrat",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "neucha",
    "label": "Neucha",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "cyrillic",
      "latin"
    ]
  },
  {
    "id": "new-rocker",
    "label": "New Rocker",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "niconne",
    "label": "Niconne",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "norican",
    "label": "Norican",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "nosifer",
    "label": "Nosifer",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "nova-mono",
    "label": "Nova Mono",
    "category": "Mono",
    "curated": false,
    "subsets": [
      "greek",
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "nova-square",
    "label": "Nova Square",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "nunito",
    "label": "Nunito",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "orbitron",
    "label": "Orbitron",
    "category": "Tech",
    "curated": true,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "oswald",
    "label": "Oswald",
    "category": "Clean",
    "curated": true,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "oxanium",
    "label": "Oxanium",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "pacifico",
    "label": "Pacifico",
    "category": "Script",
    "curated": true,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "pangolin",
    "label": "Pangolin",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "parisienne",
    "label": "Parisienne",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "passion-one",
    "label": "Passion One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "patrick-hand",
    "label": "Patrick Hand",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "patua-one",
    "label": "Patua One",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "paytone-one",
    "label": "Paytone One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "permanent-marker",
    "label": "Permanent Marker",
    "category": "Handwriting",
    "curated": true,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "pirata-one",
    "label": "Pirata One",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "pixelify-sans",
    "label": "Pixelify Sans",
    "category": "Pixel",
    "curated": false,
    "subsets": [
      "cyrillic",
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "playfair-display",
    "label": "Playfair Display",
    "category": "Serif",
    "curated": true,
    "subsets": [
      "cyrillic",
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "poppins",
    "label": "Poppins",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "devanagari",
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "press-start-2p",
    "label": "Press Start 2P",
    "category": "Pixel",
    "curated": true,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "greek",
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "quantico",
    "label": "Quantico",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "quicksand",
    "label": "Quicksand",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "racing-sans-one",
    "label": "Racing Sans One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "rajdhani",
    "label": "Rajdhani",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "devanagari",
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "ranchers",
    "label": "Ranchers",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "righteous",
    "label": "Righteous",
    "category": "Tech",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "roboto-slab",
    "label": "Roboto Slab",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "greek",
      "greek-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "rochester",
    "label": "Rochester",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "rokkitt",
    "label": "Rokkitt",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "rowdies",
    "label": "Rowdies",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "rubik",
    "label": "Rubik",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "arabic",
      "cyrillic",
      "cyrillic-ext",
      "hebrew",
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "rubik-glitch",
    "label": "Rubik Glitch",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "hebrew",
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "rubik-mono-one",
    "label": "Rubik Mono One",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "cyrillic",
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "russo-one",
    "label": "Russo One",
    "category": "Tech",
    "curated": true,
    "subsets": [
      "cyrillic",
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "rye",
    "label": "Rye",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "sacramento",
    "label": "Sacramento",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "sanchez",
    "label": "Sanchez",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "sansita-swashed",
    "label": "Sansita Swashed",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "satisfy",
    "label": "Satisfy",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "schoolbell",
    "label": "Schoolbell",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "share-tech-mono",
    "label": "Share Tech Mono",
    "category": "Mono",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "shrikhand",
    "label": "Shrikhand",
    "category": "Display",
    "curated": false,
    "subsets": [
      "gujarati",
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "sigmar-one",
    "label": "Sigmar One",
    "category": "Display",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "silkscreen",
    "label": "Silkscreen",
    "category": "Pixel",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "sniglet",
    "label": "Sniglet",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "space-mono",
    "label": "Space Mono",
    "category": "Mono",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "special-elite",
    "label": "Special Elite",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "squada-one",
    "label": "Squada One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "sriracha",
    "label": "Sriracha",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "thai",
      "vietnamese"
    ]
  },
  {
    "id": "staatliches",
    "label": "Staatliches",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "syncopate",
    "label": "Syncopate",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "teko",
    "label": "Teko",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "devanagari",
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "titan-one",
    "label": "Titan One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "titillium-web",
    "label": "Titillium Web",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "turret-road",
    "label": "Turret Road",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "ultra",
    "label": "Ultra",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "vollkorn",
    "label": "Vollkorn",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "greek",
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "vt323",
    "label": "VT323",
    "category": "Pixel",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "wallpoet",
    "label": "Wallpoet",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin"
    ]
  },
  {
    "id": "yellowtail",
    "label": "Yellowtail",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "yeseva-one",
    "label": "Yeseva One",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ]
  },
  {
    "id": "zen-dots",
    "label": "Zen Dots",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  },
  {
    "id": "zilla-slab",
    "label": "Zilla Slab",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ]
  }
];
