// AUTO-GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.
export interface FontChoice { id: string; label: string; category: string; curated: boolean; /** What the file covers, read from its cmap: names from coverage.ts (Google Fonts' subset names, and `kana`). */ subsets: string[]; /** TTF size on disk, bytes. Absent for a face injected at RUNTIME — the keychain and the pen topper both let someone drop their own font in, and that one never came from this registry. */ bytes?: number; }
export const FONTS: FontChoice[] = [
  {
    "id": "abril-fatface",
    "label": "Abril Fatface",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 67364
  },
  {
    "id": "aldrich",
    "label": "Aldrich",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 56548
  },
  {
    "id": "alegreya-sans-sc",
    "label": "Alegreya Sans SC",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 105228
  },
  {
    "id": "aleo",
    "label": "Aleo",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 61384
  },
  {
    "id": "alex-brush",
    "label": "Alex Brush",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 113384
  },
  {
    "id": "alfa-slab-one",
    "label": "Alfa Slab One",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 97376
  },
  {
    "id": "allura",
    "label": "Allura",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 109252
  },
  {
    "id": "amatic-sc",
    "label": "Amatic SC",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "cyrillic",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 141044
  },
  {
    "id": "anton",
    "label": "Anton",
    "category": "Clean",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 130324
  },
  {
    "id": "architects-daughter",
    "label": "Architects Daughter",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 28608
  },
  {
    "id": "archivo",
    "label": "Archivo",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 80036
  },
  {
    "id": "archivo-black",
    "label": "Archivo Black",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 81536
  },
  {
    "id": "arvo",
    "label": "Arvo",
    "category": "Slab",
    "curated": true,
    "subsets": [
      "latin"
    ],
    "bytes": 38780
  },
  {
    "id": "audiowide",
    "label": "Audiowide",
    "category": "Tech",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 69916
  },
  {
    "id": "bad-script",
    "label": "Bad Script",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 93280
  },
  {
    "id": "bagel-fat-one",
    "label": "Bagel Fat One",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "korean",
      "latin"
    ],
    "bytes": 764704
  },
  {
    "id": "bakbak-one",
    "label": "Bakbak One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 253240
  },
  {
    "id": "baloo-2",
    "label": "Baloo 2",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 417848
  },
  {
    "id": "bangers",
    "label": "Bangers",
    "category": "Comic",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 91216
  },
  {
    "id": "barlow-condensed",
    "label": "Barlow Condensed",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 80968
  },
  {
    "id": "bebas-neue",
    "label": "Bebas Neue",
    "category": "Clean",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 45264
  },
  {
    "id": "berkshire-swash",
    "label": "Berkshire Swash",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 58400
  },
  {
    "id": "bevan",
    "label": "Bevan",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 99264
  },
  {
    "id": "bitter",
    "label": "Bitter",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 173280
  },
  {
    "id": "black-han-sans",
    "label": "Black Han Sans",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "korean",
      "latin"
    ],
    "bytes": 324084
  },
  {
    "id": "black-ops-one",
    "label": "Black Ops One",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 162480
  },
  {
    "id": "boogaloo",
    "label": "Boogaloo",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 33960
  },
  {
    "id": "bowlby-one",
    "label": "Bowlby One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 59856
  },
  {
    "id": "bowlby-one-sc",
    "label": "Bowlby One SC",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 55200
  },
  {
    "id": "bree-serif",
    "label": "Bree Serif",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 46572
  },
  {
    "id": "bungee",
    "label": "Bungee",
    "category": "Display",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 110456
  },
  {
    "id": "bungee-inline",
    "label": "Bungee Inline",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 82056
  },
  {
    "id": "bungee-shade",
    "label": "Bungee Shade",
    "category": "Display",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 170840
  },
  {
    "id": "butcherman",
    "label": "Butcherman",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 66100
  },
  {
    "id": "cabin",
    "label": "Cabin",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 58120
  },
  {
    "id": "caveat",
    "label": "Caveat",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext"
    ],
    "bytes": 251024
  },
  {
    "id": "cedarville-cursive",
    "label": "Cedarville Cursive",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 41104
  },
  {
    "id": "chakra-petch",
    "label": "Chakra Petch",
    "category": "Tech",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 70260
  },
  {
    "id": "changa-one",
    "label": "Changa One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 22736
  },
  {
    "id": "cherry-bomb-one",
    "label": "Cherry Bomb One",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "kana",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 124292
  },
  {
    "id": "chewy",
    "label": "Chewy",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 37904
  },
  {
    "id": "chicle",
    "label": "Chicle",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 41032
  },
  {
    "id": "chonburi",
    "label": "Chonburi",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 110576
  },
  {
    "id": "cinzel",
    "label": "Cinzel",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 42676
  },
  {
    "id": "cinzel-decorative",
    "label": "Cinzel Decorative",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 60408
  },
  {
    "id": "comfortaa",
    "label": "Comfortaa",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "greek",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 137180
  },
  {
    "id": "comic-neue",
    "label": "Comic Neue",
    "category": "Comic",
    "curated": true,
    "subsets": [
      "latin"
    ],
    "bytes": 43332
  },
  {
    "id": "comic-relief",
    "label": "Comic Relief",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "cyrillic",
      "greek",
      "latin",
      "latin-ext"
    ],
    "bytes": 94684
  },
  {
    "id": "coming-soon",
    "label": "Coming Soon",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 44164
  },
  {
    "id": "concert-one",
    "label": "Concert One",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 71028
  },
  {
    "id": "cookie",
    "label": "Cookie",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 43800
  },
  {
    "id": "courgette",
    "label": "Courgette",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 122072
  },
  {
    "id": "coustard",
    "label": "Coustard",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 71748
  },
  {
    "id": "creepster",
    "label": "Creepster",
    "category": "Spooky",
    "curated": true,
    "subsets": [
      "latin"
    ],
    "bytes": 62724
  },
  {
    "id": "crete-round",
    "label": "Crete Round",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 59312
  },
  {
    "id": "cutive-mono",
    "label": "Cutive Mono",
    "category": "Mono",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 74116
  },
  {
    "id": "damion",
    "label": "Damion",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 69996
  },
  {
    "id": "dancing-script",
    "label": "Dancing Script",
    "category": "Script",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 83600
  },
  {
    "id": "days-one",
    "label": "Days One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "cyrillic",
      "latin"
    ],
    "bytes": 65580
  },
  {
    "id": "dela-gothic-one",
    "label": "Dela Gothic One",
    "category": "Display",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 43900
  },
  {
    "id": "dela-gothic-one-jp",
    "label": "Dela Gothic One JP",
    "category": "Display",
    "curated": false,
    "subsets": [
      "cyrillic",
      "greek",
      "japanese",
      "kana",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 841752
  },
  {
    "id": "delius-swash-caps",
    "label": "Delius Swash Caps",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 63052
  },
  {
    "id": "dm-mono",
    "label": "DM Mono",
    "category": "Mono",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 40540
  },
  {
    "id": "do-hyeon",
    "label": "Do Hyeon",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "korean",
      "latin"
    ],
    "bytes": 308380
  },
  {
    "id": "domine",
    "label": "Domine",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 64296
  },
  {
    "id": "dotgothic16",
    "label": "DotGothic16",
    "category": "Pixel",
    "curated": false,
    "subsets": [
      "cyrillic",
      "japanese",
      "kana",
      "latin"
    ],
    "bytes": 704924
  },
  {
    "id": "eater",
    "label": "Eater",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 83928
  },
  {
    "id": "eb-garamond",
    "label": "EB Garamond",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 205696
  },
  {
    "id": "electrolize",
    "label": "Electrolize",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 55712
  },
  {
    "id": "ewert",
    "label": "Ewert",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 70752
  },
  {
    "id": "exo-2",
    "label": "Exo 2",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 70192
  },
  {
    "id": "faster-one",
    "label": "Faster One",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 94044
  },
  {
    "id": "faustina",
    "label": "Faustina",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 53352
  },
  {
    "id": "figtree",
    "label": "Figtree",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 33516
  },
  {
    "id": "fira-mono",
    "label": "Fira Mono",
    "category": "Mono",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 49324
  },
  {
    "id": "fjalla-one",
    "label": "Fjalla One",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 206432
  },
  {
    "id": "flavors",
    "label": "Flavors",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 184784
  },
  {
    "id": "fredoka",
    "label": "Fredoka",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 48856
  },
  {
    "id": "frijole",
    "label": "Frijole",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 227860
  },
  {
    "id": "fugaz-one",
    "label": "Fugaz One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 27868
  },
  {
    "id": "gaegu",
    "label": "Gaegu",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "korean",
      "latin"
    ],
    "bytes": 1668076
  },
  {
    "id": "gasoek-one",
    "label": "Gasoek One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "korean",
      "latin"
    ],
    "bytes": 408684
  },
  {
    "id": "gelasio",
    "label": "Gelasio",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 82972
  },
  {
    "id": "gloria-hallelujah",
    "label": "Gloria Hallelujah",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 44364
  },
  {
    "id": "gochi-hand",
    "label": "Gochi Hand",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 37352
  },
  {
    "id": "gothic-a1",
    "label": "Gothic A1",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "greek",
      "kana",
      "korean",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 455064
  },
  {
    "id": "grand-hotel",
    "label": "Grand Hotel",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 65012
  },
  {
    "id": "grandstander",
    "label": "Grandstander",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 83368
  },
  {
    "id": "gravitas-one",
    "label": "Gravitas One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 41448
  },
  {
    "id": "great-vibes",
    "label": "Great Vibes",
    "category": "Script",
    "curated": false,
    "subsets": [
      "cyrillic",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 362736
  },
  {
    "id": "griffy",
    "label": "Griffy",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 208776
  },
  {
    "id": "gruppo",
    "label": "Gruppo",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 72296
  },
  {
    "id": "handjet",
    "label": "Handjet",
    "category": "Pixel",
    "curated": false,
    "subsets": [
      "armenian",
      "cyrillic",
      "cyrillic-ext",
      "greek",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 183616
  },
  {
    "id": "handlee",
    "label": "Handlee",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 39132
  },
  {
    "id": "henny-penny",
    "label": "Henny Penny",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 92596
  },
  {
    "id": "homemade-apple",
    "label": "Homemade Apple",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 102516
  },
  {
    "id": "ibm-plex-mono",
    "label": "IBM Plex Mono",
    "category": "Mono",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 135580
  },
  {
    "id": "iceland",
    "label": "Iceland",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 47632
  },
  {
    "id": "inconsolata",
    "label": "Inconsolata",
    "category": "Mono",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 60836
  },
  {
    "id": "indie-flower",
    "label": "Indie Flower",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 45496
  },
  {
    "id": "inter",
    "label": "Inter",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 143012
  },
  {
    "id": "italianno",
    "label": "Italianno",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 103668
  },
  {
    "id": "itim",
    "label": "Itim",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 258028
  },
  {
    "id": "jersey-15",
    "label": "Jersey 15",
    "category": "Pixel",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 98424
  },
  {
    "id": "jersey-25",
    "label": "Jersey 25",
    "category": "Pixel",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 135932
  },
  {
    "id": "jetbrains-mono",
    "label": "JetBrains Mono",
    "category": "Mono",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 69324
  },
  {
    "id": "jolly-lodger",
    "label": "Jolly Lodger",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 39800
  },
  {
    "id": "josefin-sans",
    "label": "Josefin Sans",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 53488
  },
  {
    "id": "josefin-slab",
    "label": "Josefin Slab",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 21220
  },
  {
    "id": "jua",
    "label": "Jua",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "korean",
      "latin"
    ],
    "bytes": 1328968
  },
  {
    "id": "jura",
    "label": "Jura",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "cyrillic",
      "greek",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 151212
  },
  {
    "id": "just-another-hand",
    "label": "Just Another Hand",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 108352
  },
  {
    "id": "kalam",
    "label": "Kalam",
    "category": "Handwriting",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 426488
  },
  {
    "id": "kanit",
    "label": "Kanit",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 168768
  },
  {
    "id": "kaushan-script",
    "label": "Kaushan Script",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 210672
  },
  {
    "id": "khand",
    "label": "Khand",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 48884
  },
  {
    "id": "kreon",
    "label": "Kreon",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 35452
  },
  {
    "id": "lacquer",
    "label": "Lacquer",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 197316
  },
  {
    "id": "lexend",
    "label": "Lexend",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 99892
  },
  {
    "id": "libre-baskerville",
    "label": "Libre Baskerville",
    "category": "Serif",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 152072
  },
  {
    "id": "lilita-one",
    "label": "Lilita One",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 28092
  },
  {
    "id": "literata",
    "label": "Literata",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 90564
  },
  {
    "id": "lobster",
    "label": "Lobster",
    "category": "Script",
    "curated": true,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 406076
  },
  {
    "id": "lobster-two",
    "label": "Lobster Two",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 254332
  },
  {
    "id": "lora",
    "label": "Lora",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 188336
  },
  {
    "id": "luckiest-guy",
    "label": "Luckiest Guy",
    "category": "Comic",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 56860
  },
  {
    "id": "m-plus-1p",
    "label": "M PLUS 1p",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "greek",
      "japanese",
      "kana",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 850944
  },
  {
    "id": "major-mono-display",
    "label": "Major Mono Display",
    "category": "Mono",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 123028
  },
  {
    "id": "mali",
    "label": "Mali",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 60512
  },
  {
    "id": "manrope",
    "label": "Manrope",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 56140
  },
  {
    "id": "marcellus",
    "label": "Marcellus",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 46004
  },
  {
    "id": "marck-script",
    "label": "Marck Script",
    "category": "Script",
    "curated": false,
    "subsets": [
      "cyrillic",
      "latin",
      "latin-ext"
    ],
    "bytes": 83664
  },
  {
    "id": "martian-mono",
    "label": "Martian Mono",
    "category": "Mono",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 36280
  },
  {
    "id": "merriweather",
    "label": "Merriweather",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 156096
  },
  {
    "id": "metal-mania",
    "label": "Metal Mania",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 226708
  },
  {
    "id": "michroma",
    "label": "Michroma",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 55944
  },
  {
    "id": "micro-5",
    "label": "Micro 5",
    "category": "Pixel",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 49724
  },
  {
    "id": "modak",
    "label": "Modak",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 644584
  },
  {
    "id": "monoton",
    "label": "Monoton",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 51604
  },
  {
    "id": "montserrat",
    "label": "Montserrat",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 180068
  },
  {
    "id": "neucha",
    "label": "Neucha",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "cyrillic",
      "latin"
    ],
    "bytes": 103260
  },
  {
    "id": "new-rocker",
    "label": "New Rocker",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 173224
  },
  {
    "id": "niconne",
    "label": "Niconne",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 45616
  },
  {
    "id": "norican",
    "label": "Norican",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 73740
  },
  {
    "id": "nosifer",
    "label": "Nosifer",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 43272
  },
  {
    "id": "nothing-you-could-do",
    "label": "Nothing You Could Do",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 26800
  },
  {
    "id": "noto-sans-sc",
    "label": "Noto Sans SC",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "chinese-simplified",
      "cyrillic",
      "latin",
      "vietnamese"
    ],
    "bytes": 1201664
  },
  {
    "id": "nova-mono",
    "label": "Nova Mono",
    "category": "Mono",
    "curated": false,
    "subsets": [
      "greek",
      "latin",
      "latin-ext"
    ],
    "bytes": 302380
  },
  {
    "id": "nova-square",
    "label": "Nova Square",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 87968
  },
  {
    "id": "nunito",
    "label": "Nunito",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 125528
  },
  {
    "id": "orbitron",
    "label": "Orbitron",
    "category": "Tech",
    "curated": true,
    "subsets": [
      "latin"
    ],
    "bytes": 36340
  },
  {
    "id": "oswald",
    "label": "Oswald",
    "category": "Clean",
    "curated": true,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 86068
  },
  {
    "id": "outfit",
    "label": "Outfit",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 45888
  },
  {
    "id": "oxanium",
    "label": "Oxanium",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 26044
  },
  {
    "id": "pacifico",
    "label": "Pacifico",
    "category": "Script",
    "curated": true,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 251232
  },
  {
    "id": "pangolin",
    "label": "Pangolin",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 588736
  },
  {
    "id": "parisienne",
    "label": "Parisienne",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 61248
  },
  {
    "id": "passion-one",
    "label": "Passion One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 24940
  },
  {
    "id": "patrick-hand",
    "label": "Patrick Hand",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 152636
  },
  {
    "id": "patua-one",
    "label": "Patua One",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 35624
  },
  {
    "id": "paytone-one",
    "label": "Paytone One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 114648
  },
  {
    "id": "permanent-marker",
    "label": "Permanent Marker",
    "category": "Handwriting",
    "curated": true,
    "subsets": [
      "latin"
    ],
    "bytes": 70600
  },
  {
    "id": "petit-formal-script",
    "label": "Petit Formal Script",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 175068
  },
  {
    "id": "petrona",
    "label": "Petrona",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 80080
  },
  {
    "id": "pinyon-script",
    "label": "Pinyon Script",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 133508
  },
  {
    "id": "pirata-one",
    "label": "Pirata One",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 56316
  },
  {
    "id": "pixelify-sans",
    "label": "Pixelify Sans",
    "category": "Pixel",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 49840
  },
  {
    "id": "playfair-display",
    "label": "Playfair Display",
    "category": "Serif",
    "curated": true,
    "subsets": [
      "cyrillic",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 210208
  },
  {
    "id": "podkova",
    "label": "Podkova",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 54244
  },
  {
    "id": "poppins",
    "label": "Poppins",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 154628
  },
  {
    "id": "press-start-2p",
    "label": "Press Start 2P",
    "category": "Pixel",
    "curated": true,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "greek",
      "latin",
      "latin-ext"
    ],
    "bytes": 118204
  },
  {
    "id": "pt-serif",
    "label": "PT Serif",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext"
    ],
    "bytes": 359048
  },
  {
    "id": "quantico",
    "label": "Quantico",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 20940
  },
  {
    "id": "quicksand",
    "label": "Quicksand",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 110268
  },
  {
    "id": "racing-sans-one",
    "label": "Racing Sans One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 145796
  },
  {
    "id": "rajdhani",
    "label": "Rajdhani",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 351464
  },
  {
    "id": "raleway",
    "label": "Raleway",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 132000
  },
  {
    "id": "rammetto-one",
    "label": "Rammetto One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 69392
  },
  {
    "id": "ranchers",
    "label": "Ranchers",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 167420
  },
  {
    "id": "reenie-beanie",
    "label": "Reenie Beanie",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 85048
  },
  {
    "id": "righteous",
    "label": "Righteous",
    "category": "Tech",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 43104
  },
  {
    "id": "roboto-mono",
    "label": "Roboto Mono",
    "category": "Mono",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 34068
  },
  {
    "id": "roboto-slab",
    "label": "Roboto Slab",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "greek",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 101564
  },
  {
    "id": "rochester",
    "label": "Rochester",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 33456
  },
  {
    "id": "rock-salt",
    "label": "Rock Salt",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 115160
  },
  {
    "id": "rokkitt",
    "label": "Rokkitt",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 68668
  },
  {
    "id": "rowdies",
    "label": "Rowdies",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 74648
  },
  {
    "id": "rubik",
    "label": "Rubik",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext"
    ],
    "bytes": 174992
  },
  {
    "id": "rubik-beastly",
    "label": "Rubik Beastly",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 268916
  },
  {
    "id": "rubik-burned",
    "label": "Rubik Burned",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 311008
  },
  {
    "id": "rubik-distressed",
    "label": "Rubik Distressed",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 454716
  },
  {
    "id": "rubik-glitch",
    "label": "Rubik Glitch",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext"
    ],
    "bytes": 384304
  },
  {
    "id": "rubik-mono-one",
    "label": "Rubik Mono One",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "cyrillic",
      "latin"
    ],
    "bytes": 116664
  },
  {
    "id": "rubik-moonrocks",
    "label": "Rubik Moonrocks",
    "category": "Spooky",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 208776
  },
  {
    "id": "rubik-one",
    "label": "Rubik One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "cyrillic",
      "latin",
      "latin-ext"
    ],
    "bytes": 153084
  },
  {
    "id": "rubik-puddles",
    "label": "Rubik Puddles",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 207080
  },
  {
    "id": "rubik-spray-paint",
    "label": "Rubik Spray Paint",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 488608
  },
  {
    "id": "rubik-storm",
    "label": "Rubik Storm",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 402580
  },
  {
    "id": "rubik-vinyl",
    "label": "Rubik Vinyl",
    "category": "Spooky",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 216604
  },
  {
    "id": "rufina",
    "label": "Rufina",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 40040
  },
  {
    "id": "russo-one",
    "label": "Russo One",
    "category": "Tech",
    "curated": true,
    "subsets": [
      "cyrillic",
      "latin",
      "latin-ext"
    ],
    "bytes": 39124
  },
  {
    "id": "rye",
    "label": "Rye",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 183244
  },
  {
    "id": "sacramento",
    "label": "Sacramento",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 79696
  },
  {
    "id": "saira-condensed",
    "label": "Saira Condensed",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 95068
  },
  {
    "id": "sanchez",
    "label": "Sanchez",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 72552
  },
  {
    "id": "sancreek",
    "label": "Sancreek",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 93252
  },
  {
    "id": "sansita",
    "label": "Sansita",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 103316
  },
  {
    "id": "sansita-swashed",
    "label": "Sansita Swashed",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 112236
  },
  {
    "id": "satisfy",
    "label": "Satisfy",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 44416
  },
  {
    "id": "schoolbell",
    "label": "Schoolbell",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 45280
  },
  {
    "id": "secular-one",
    "label": "Secular One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 59952
  },
  {
    "id": "shadows-into-light",
    "label": "Shadows Into Light",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 38608
  },
  {
    "id": "share-tech-mono",
    "label": "Share Tech Mono",
    "category": "Mono",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 43272
  },
  {
    "id": "short-stack",
    "label": "Short Stack",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 68152
  },
  {
    "id": "shrikhand",
    "label": "Shrikhand",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 213200
  },
  {
    "id": "sigmar-one",
    "label": "Sigmar One",
    "category": "Display",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 165016
  },
  {
    "id": "silkscreen",
    "label": "Silkscreen",
    "category": "Pixel",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 30684
  },
  {
    "id": "sixtyfour",
    "label": "Sixtyfour",
    "category": "Pixel",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 19692
  },
  {
    "id": "sniglet",
    "label": "Sniglet",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 75212
  },
  {
    "id": "sora",
    "label": "Sora",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 42040
  },
  {
    "id": "source-code-pro",
    "label": "Source Code Pro",
    "category": "Mono",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "greek",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 212880
  },
  {
    "id": "space-mono",
    "label": "Space Mono",
    "category": "Mono",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 81124
  },
  {
    "id": "special-elite",
    "label": "Special Elite",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 145808
  },
  {
    "id": "spectral",
    "label": "Spectral",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 90136
  },
  {
    "id": "squada-one",
    "label": "Squada One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 19072
  },
  {
    "id": "sriracha",
    "label": "Sriracha",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 308668
  },
  {
    "id": "staatliches",
    "label": "Staatliches",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 52480
  },
  {
    "id": "sue-ellen-francisco",
    "label": "Sue Ellen Francisco",
    "category": "Handwriting",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 31976
  },
  {
    "id": "syncopate",
    "label": "Syncopate",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 135968
  },
  {
    "id": "syne-mono",
    "label": "Syne Mono",
    "category": "Mono",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 48280
  },
  {
    "id": "tangerine",
    "label": "Tangerine",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 54656
  },
  {
    "id": "teko",
    "label": "Teko",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 153772
  },
  {
    "id": "tiny5",
    "label": "Tiny5",
    "category": "Pixel",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 85984
  },
  {
    "id": "titan-one",
    "label": "Titan One",
    "category": "Display",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 55712
  },
  {
    "id": "titillium-web",
    "label": "Titillium Web",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 51244
  },
  {
    "id": "tomorrow",
    "label": "Tomorrow",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 44020
  },
  {
    "id": "turret-road",
    "label": "Turret Road",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 40764
  },
  {
    "id": "ultra",
    "label": "Ultra",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 49024
  },
  {
    "id": "unica-one",
    "label": "Unica One",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 53232
  },
  {
    "id": "urbanist",
    "label": "Urbanist",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 35472
  },
  {
    "id": "vollkorn",
    "label": "Vollkorn",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "greek",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 228856
  },
  {
    "id": "vt323",
    "label": "VT323",
    "category": "Pixel",
    "curated": true,
    "subsets": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 147320
  },
  {
    "id": "wallpoet",
    "label": "Wallpoet",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 39904
  },
  {
    "id": "work-sans",
    "label": "Work Sans",
    "category": "Clean",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 85888
  },
  {
    "id": "workbench",
    "label": "Workbench",
    "category": "Pixel",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 19820
  },
  {
    "id": "xanh-mono",
    "label": "Xanh Mono",
    "category": "Mono",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 48048
  },
  {
    "id": "yellowtail",
    "label": "Yellowtail",
    "category": "Script",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 58428
  },
  {
    "id": "yeseva-one",
    "label": "Yeseva One",
    "category": "Serif",
    "curated": false,
    "subsets": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "bytes": 108016
  },
  {
    "id": "zcool-kuaile",
    "label": "ZCOOL KuaiLe",
    "category": "Comic",
    "curated": false,
    "subsets": [
      "chinese-simplified",
      "latin"
    ],
    "bytes": 760036
  },
  {
    "id": "zen-dots",
    "label": "Zen Dots",
    "category": "Tech",
    "curated": false,
    "subsets": [
      "latin"
    ],
    "bytes": 33856
  },
  {
    "id": "zilla-slab",
    "label": "Zilla Slab",
    "category": "Slab",
    "curated": false,
    "subsets": [
      "latin",
      "latin-ext"
    ],
    "bytes": 128164
  }
];
