import { zipSync, strToU8 } from 'fflate';
import { BRAND } from '@vostok/brand';
import type { PartMesh } from '../types';

const f = (n: number): string => String(Math.round(n * 1e4) / 1e4);

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const VL_NS = 'https://vostoklabs.com/3mf/2026';

function hex(rgb: [number, number, number]): string {
  const h = (v: number) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, '0');
  return `#${h(rgb[0])}${h(rgb[1])}${h(rgb[2])}FF`;
}

function assignExtruders(parts: PartMesh[]): number[] {
  const slotByColor = new Map<string, number>();
  return parts.map((p) => {
    const key = p.colorRgb.join(',');
    let slot = slotByColor.get(key);
    if (slot === undefined) {
      slot = slotByColor.size + 1;
      slotByColor.set(key, slot);
    }
    return slot;
  });
}

function meshXml(p: PartMesh, minZ: number): string {
  const vp = p.vertProperties;
  const tv = p.triVerts;
  const verts: string[] = [];
  for (let i = 0; i < vp.length; i += 3) {
    verts.push(`<vertex x="${f(vp[i]!)}" y="${f(vp[i + 1]!)}" z="${f(vp[i + 2]! - minZ)}"/>`);
  }
  const tris: string[] = [];
  for (let i = 0; i < tv.length; i += 3) {
    tris.push(`<triangle v1="${tv[i]!}" v2="${tv[i + 1]!}" v3="${tv[i + 2]!}"/>`);
  }
  return `<mesh><vertices>${verts.join('')}</vertices><triangles>${tris.join('')}</triangles></mesh>`;
}

export function buildThreeMF(parts: PartMesh[]): Uint8Array {
  // Drop the whole assembly onto the build plate (min Z -> 0)
  let minZ = Infinity;
  for (const p of parts) {
    for (let i = 2; i < p.vertProperties.length; i += 3) {
      if (p.vertProperties[i]! < minZ) minZ = p.vertProperties[i]!;
    }
  }
  if (!isFinite(minZ)) minZ = 0;

  const extruders = assignExtruders(parts);

  const baseMaterials = parts
    .map((p) => `<base name="${p.name}" displaycolor="${hex(p.colorRgb)}"/>`)
    .join('');

  const leafObjects = parts
    .map((p, i) => `<object id="${i + 2}" type="model" pid="1" pindex="${i}">${meshXml(p, minZ)}</object>`)
    .join('');

  const firstWrapperId = parts.length + 2;
  const comps = parts.map((_, i) => `<component objectid="${i + 2}"/>`).join('');
  const wrapperObject = `<object id="${firstWrapperId}" type="model"><components>${comps}</components></object>`;

  const buildItems = `<item objectid="${firstWrapperId}"/>`;

  const creationDate = new Date().toISOString().slice(0, 10);
  
  // Embed CC commercial terms and provenance
  const metadata =
    `<metadata name="Title">Name Keychain</metadata>` +
    `<metadata name="Designer">Vostok Labs</metadata>` +
    `<metadata name="Application">Vostok Labs Name Keychain Generator</metadata>` +
    `<metadata name="CreationDate">${creationDate}</metadata>` +
    `<metadata name="Copyright">${esc('© Vostok Labs. Generated by the Vostok Labs Name Keychain Generator.')}</metadata>` +
    `<metadata name="LicenseTerms">${esc(`Free for personal use only. Selling prints or redistributing requires a commercial license: ${BRAND.urls.mwCommercial}`)}</metadata>` +
    `<metadata name="vl:generator">name-keychain-generator</metadata>`;

  const model =
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<model unit="millimeter" xml:lang="en-US"` +
    ` xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02"` +
    ` xmlns:m="http://schemas.microsoft.com/3dmanufacturing/material/2015/02"` +
    ` xmlns:vl="${VL_NS}">` +
    metadata +
    `<resources>` +
    `<basematerials id="1">${baseMaterials}</basematerials>` +
    leafObjects +
    wrapperObject +
    `</resources>` +
    `<build>${buildItems}</build>` +
    `</model>`;

  const partsCfg = parts
    .map((p, i) =>
      `<part id="${i + 2}" subtype="normal_part">` +
      `<metadata key="name" value="${p.name}"/>` +
      `<metadata key="extruder" value="${extruders[i]}"/>` +
      `</part>`,
    )
    .join('');

  const objectCfg =
    `<object id="${firstWrapperId}">` +
    `<metadata key="name" value="name_keychain"/>` +
    `<metadata key="extruder" value="1"/>` +
    partsCfg +
    `</object>`;

  const modelSettings =
    `<?xml version="1.0" encoding="UTF-8"?>\n` + `<config>` + objectCfg + `</config>`;

  const contentTypes =
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">` +
    `<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>` +
    `<Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>` +
    `<Default Extension="config" ContentType="text/xml"/>` +
    `</Types>`;

  const rels =
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
    `<Relationship Target="/3D/3dmodel.model" Id="rel0"` +
    ` Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>` +
    `</Relationships>`;

  const provenance = [
    'Vostok Labs — Name Keychain Generator',
    '',
    'This 3MF was generated by the Vostok Labs Name Keychain Generator.',
    `Created: ${creationDate}`,
    '',
    'License: free for personal use only.',
    'Commercial use (selling printed designs) requires a membership license:',
    BRAND.urls.mwCommercial,
    '',
    'Provenance / licensing questions: ' + BRAND.urls.makerworld,
  ].join('\n');

  return zipSync(
    {
      '[Content_Types].xml': strToU8(contentTypes),
      '_rels/.rels': strToU8(rels),
      '3D/3dmodel.model': strToU8(model),
      'Metadata/model_settings.config': strToU8(modelSettings),
      'Metadata/vostok_labs.txt': strToU8(provenance),
    },
    { level: 6 },
  );
}

export function downloadThreeMF(parts: PartMesh[], fileName = 'keychain.3mf') {
  const bytes = buildThreeMF(parts);
  const blob = new Blob([bytes as unknown as BlobPart], { type: 'model/3mf' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
