/*
  The asset registry: every font, typeface, icon set, symbol set, pattern set and model an app
  bundles, with where it came from and the licence it ships under.

    assets.json           rows for published files (committed, like generators.json)
    assets.private.json   rows for gitignored files (gitignored), so no committed file names one

  A row is { id, kind, files: { path: sha256 }, licence, copyright, reservedNames, shipsAs,
  source: { url, commit }, licenceUrl, notice, writtenBy }. `licence` is an SPDX expression;
  `shipsAs` is "original" (the upstream file, byte for byte), "cut" (a subset or an instance of
  it) or "converted" (the same outlines or data in another format); `notice` lists the licence
  texts that travel with it. A copy of a file elsewhere in the repo is claimed by its sha256, so
  the row lists only the files its writer manages. Which apps carry a row is derived from their
  source (scripts/lib/bundle.mjs), never stored.

  Written by packages/fonts/scripts/fetch-fonts.mjs (the faces it fetches, with their family's
  licence read upstream) and by scripts/assets.mjs (everything else). Checked by
  scripts/check-assets.mjs.
*/

import { readFileSync, writeFileSync, existsSync, unlinkSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { brotliDecompressSync, inflateSync } from 'node:zlib';
import { abs, ignored } from './source.mjs';

/** The licences anything shipped may carry (CLAUDE.md, invariant #6). An OFL face may not be
 *  shipped modified under a name its licence reserves. */
export const ALLOWED = ['OFL-1.1', 'Apache-2.0', 'MIT', 'ISC', 'CC0-1.0'];

export const REGISTRY = 'assets.json';
export const PRIVATE_REGISTRY = 'assets.private.json';

const ORDER = ['id', 'kind', 'files', 'licence', 'copyright', 'reservedNames', 'shipsAs', 'source', 'licenceUrl', 'notice', 'writtenBy'];
const COMMENT = 'Generated by scripts/assets.mjs and packages/fonts/scripts/fetch-fonts.mjs; do not edit by hand. pnpm check:assets holds every font, typeface, symbol, pattern and model file to a row here.';

/** What kind of asset a file is by its name, or null for a file the check does not hold to a
 *  row: fonts, three.js typefaces, models, and the data of a symbol or pattern set. */
export function assetKind(path) {
  if (/\.(?:ttf|otf|woff2?)$/i.test(path)) return 'font';
  if (/\.typeface\.json$/i.test(path)) return 'typeface';
  if (/\.onnx$/i.test(path)) return 'model';
  if (/(?:^|\/)(?:symbols|patterns)\/(?:.*\/)?[^/]+\.json$/i.test(path)) return 'data';
  return null;
}

export const sha256 = (buf) => createHash('sha256').update(buf).digest('hex');

/** Text files are hashed with LF line ends, as git stores them: a Windows checkout turns each
 *  LF into CRLF, which is not a change to the file. Fonts, models and other binaries are hashed
 *  as they are. */
const TEXT = /\.(?:json|[cm]?[jt]sx?|svg|txt|md|css|html)$/i;

/** The sha256 a row records for a repo file. */
export function fileHash(path, buf = readFileSync(abs(path))) {
  if (!TEXT.test(path)) return sha256(buf);
  const lf = Buffer.alloc(buf.length);
  let n = 0;
  for (let i = 0; i < buf.length; i++) if (!(buf[i] === 0x0d && buf[i + 1] === 0x0a)) lf[n++] = buf[i];
  return sha256(lf.subarray(0, n));
}

/** Whether an SPDX expression is allowed: every term of an AND, at least one of an OR. */
export function licenceAllowed(expr) {
  const text = String(expr ?? '').trim();
  if (!text || /[()]/.test(text)) return false;
  return text.split(/\s+OR\s+/).some((alt) => alt.split(/\s+AND\s+/).every((id) => ALLOWED.includes(id.trim())));
}

/** Code-point order, the same on every machine (localeCompare follows the system's locale). */
const byCode = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

const readJson = (rel) => (existsSync(abs(rel)) ? JSON.parse(readFileSync(abs(rel), 'utf8')) : null);

/** Every row, the private file's merged in: a row in both has the files of both. */
export function readRegistry() {
  const byId = new Map();
  for (const file of [REGISTRY, PRIVATE_REGISTRY]) {
    for (const row of readJson(file)?.assets ?? []) {
      const had = byId.get(row.id);
      if (had) had.files = { ...had.files, ...row.files };
      else byId.set(row.id, { ...row, files: { ...row.files } });
    }
  }
  return [...byId.values()];
}

/** Every file the published registry names. */
export const publicPaths = () => (readJson(REGISTRY)?.assets ?? []).flatMap((row) => Object.keys(row.files));

/** Writes the rows: each row's published files to assets.json and its gitignored ones to
 *  assets.private.json, under the same id. The private file is written only where there is
 *  something private to say. */
export function writeRegistry(rows) {
  const paths = rows.flatMap((r) => Object.keys(r.files));
  const hidden = ignored(paths);
  // One key order for every row, whoever wrote it.
  const ordered = (row) => Object.fromEntries(Object.entries(row).sort(([a], [b]) => ((ORDER.indexOf(a) + 1 || 99) - (ORDER.indexOf(b) + 1 || 99))));
  const half = (keep) => rows
    .map((row) => ordered({ ...row, files: Object.fromEntries(Object.entries(row.files).filter(([p]) => keep(hidden.has(p))).sort(([a], [b]) => byCode(a, b))) }))
    .filter((row) => Object.keys(row.files).length)
    .sort((a, b) => byCode(a.id, b.id));
  const text = (assets) => `${JSON.stringify({ $comment: COMMENT, assets }, null, 2)}\n`;
  writeFileSync(abs(REGISTRY), text(half((h) => !h)));
  const privateRows = half((h) => h);
  if (privateRows.length) writeFileSync(abs(PRIVATE_REGISTRY), text(privateRows));
  else if (existsSync(abs(PRIVATE_REGISTRY))) unlinkSync(abs(PRIVATE_REGISTRY));
}

/** Replaces every row `writtenBy` wrote with `rows`, keeping everyone else's. */
export function recordAssets(writtenBy, rows) {
  const kept = readRegistry().filter((r) => r.writtenBy !== writtenBy);
  writeRegistry([...kept, ...rows.map((r) => ({ ...r, writtenBy }))]);
}

const hashes = new Map();
/** `fileHash` of a repo file, read once. */
export function hashOf(path) {
  if (!hashes.has(path)) hashes.set(path, fileHash(path));
  return hashes.get(path);
}

/** The ids of the rows that claim any of `files` (repo paths, such as what an app's build
 *  reaches): by the path a row names, or by the bytes of a copy. */
export function rowsClaiming(files, rows = readRegistry()) {
  const byPath = new Map();
  const byHash = new Map();
  for (const row of rows) {
    for (const [path, hash] of Object.entries(row.files)) {
      byPath.set(path, [...(byPath.get(path) ?? []), row.id]);
      byHash.set(hash, [...(byHash.get(hash) ?? []), row.id]);
    }
  }
  const ids = new Set();
  for (const path of files) {
    const named = byPath.get(path);
    if (named) for (const id of named) ids.add(id);
    else if (assetKind(path) && existsSync(abs(path))) for (const id of byHash.get(hashOf(path)) ?? []) ids.add(id);
  }
  return ids;
}

// ─────────────────────────── licence text inside a file ───────────────────────────

/** The strings of a font's name table by name ID: Windows English first, then any Unicode
 *  record, then Macintosh. */
function nameTable(t) {
  const out = {};
  const score = {};
  const count = t.readUInt16BE(2);
  const storage = t.readUInt16BE(4);
  for (let i = 0; i < count; i++) {
    const r = 6 + i * 12;
    const platform = t.readUInt16BE(r);
    const lang = t.readUInt16BE(r + 4);
    const id = t.readUInt16BE(r + 6);
    const raw = t.subarray(storage + t.readUInt16BE(r + 10), storage + t.readUInt16BE(r + 10) + t.readUInt16BE(r + 8));
    const text = platform === 1 ? raw.toString('latin1') : Buffer.from(raw.subarray(0, raw.length & ~1)).swap16().toString('utf16le');
    const s = platform === 3 && lang === 0x409 ? 2 : platform === 3 || platform === 0 ? 1 : 0;
    if (!(id in out) || s > score[id]) { out[id] = text; score[id] = s; }
  }
  return out;
}

/** The name table of an sfnt (TrueType or OpenType) file. */
function sfntNames(buf) {
  for (let i = 0, n = buf.readUInt16BE(4); i < n; i++) {
    const r = 12 + i * 16;
    if (buf.toString('latin1', r, r + 4) === 'name') return nameTable(buf.subarray(buf.readUInt32BE(r + 8), buf.readUInt32BE(r + 8) + buf.readUInt32BE(r + 12)));
  }
  return {};
}

/** WOFF 1: each table zlib-compressed on its own. */
function woffNames(buf) {
  for (let i = 0, n = buf.readUInt16BE(12); i < n; i++) {
    const r = 44 + i * 20;
    if (buf.toString('latin1', r, r + 4) !== 'name') continue;
    const data = buf.subarray(buf.readUInt32BE(r + 4), buf.readUInt32BE(r + 4) + buf.readUInt32BE(r + 8));
    return nameTable(buf.readUInt32BE(r + 8) < buf.readUInt32BE(r + 12) ? inflateSync(data) : data);
  }
  return {};
}

/** The tags a WOFF2 table directory names by index (the WOFF2 specification, 5.1). */
const WOFF2_TAGS = 'cmap head hhea hmtx maxp name OS/2 post cvt  fpgm glyf loca prep CFF  VORG EBDT EBLC gasp hdmx kern LTSH PCLT VDMX vhea vmtx BASE GDEF GPOS GSUB EBSC JSTF MATH CBDT CBLC COLR CPAL SVG  sbix acnt avar bdat bloc bsln cvar fdsc feat fmtx fvar gvar hsty just lcar mort morx opbd prop trak Zapf Silf Glat Gloc Feat Sill'.match(/.{4}\s?/g).map((t) => t.slice(0, 4));

/** WOFF2: one Brotli stream holding every table in directory order. The name table is never
 *  transformed, so it can be read straight out of the stream. */
function woff2Names(buf) {
  let p = 48;
  const varint = () => {
    let v = 0;
    for (let i = 0; i < 5; i++) {
      const b = buf[p++];
      v = v * 128 + (b & 0x7f);
      if (!(b & 0x80)) return v;
    }
    throw new Error('bad WOFF2 table directory');
  };
  const tables = [];
  for (let i = 0, n = buf.readUInt16BE(12); i < n; i++) {
    const flags = buf[p++];
    const tag = (flags & 0x3f) === 63 ? buf.toString('latin1', p, (p += 4)) : WOFF2_TAGS[flags & 0x3f];
    const length = varint();
    const version = flags >> 6;
    const transformed = tag === 'glyf' || tag === 'loca' ? version !== 3 : version !== 0;
    tables.push({ tag, length: transformed ? varint() : length });
  }
  const stream = brotliDecompressSync(buf.subarray(p, p + buf.readUInt32BE(20)));
  let at = 0;
  for (const t of tables) {
    if (t.tag === 'name') return nameTable(stream.subarray(at, at + t.length));
    at += t.length;
  }
  return {};
}

/** A font file's name table, whatever its container. */
export function fontNames(buf) {
  const sig = buf.toString('latin1', 0, 4);
  if (sig === 'wOF2') return woff2Names(buf);
  if (sig === 'wOFF') return woffNames(buf);
  return sfntNames(buf);
}

/** What a file says about its own licence and names: a font's name table, a typeface's
 *  `original_font_information`, a data set's own `licence` field. Empty for a file that says
 *  nothing (a model). */
export function embedded(path, buf) {
  const kind = assetKind(path);
  if (kind === 'font') {
    const n = fontNames(buf);
    return { names: [n[1], n[4], n[6], n[16]].filter(Boolean), copyright: n[0] ?? '', licence: [n[0], n[13], n[14]].filter(Boolean).join('\n') };
  }
  if (kind === 'typeface') {
    const i = JSON.parse(buf.toString('utf8')).original_font_information ?? {};
    return {
      names: [i.font_family_name, i.full_font_name, i.postscript_name].filter(Boolean),
      copyright: i.copyright ?? '',
      licence: [i.copyright, i.license_description, i.license_url].filter(Boolean).join('\n'),
    };
  }
  if (kind === 'data') {
    const head = buf.subarray(0, 2048).toString('utf8');
    const m = head.match(/"licen[cs]e"\s*:\s*"([^"]*)"/i);
    return { names: [], copyright: '', licence: m ? m[1] : '' };
  }
  return { names: [], copyright: '', licence: '' };
}

/** Licence terms none of the allowed licences has: what a row claiming one of them must not
 *  find in the file it claims. */
const FORBIDDEN = [
  [/\beula|end[- ]user\s+licen[cs]e/i, 'an end-user licence agreement'],
  [/\bpersonal\b(?:\s+\w+){0,4}\s+use\b/i, 'personal-use terms'],
  [/non-?\s?commercial/i, 'non-commercial terms'],
  [/no\s*-?\s*deriv/i, 'no-derivatives terms'],
  [/\bL?GPL\b|GNU\s+(?:Lesser\s+|Library\s+)?General\s+Public\s+Licen[cs]e/i, 'the GPL'],
  [/creative\s+commons\s+attribution|\bCC[- ]BY\b/i, 'CC BY'],
];
/** How a file names an allowed licence. */
const NAMED = [
  ['OFL-1.1', /SIL Open Font Licen[cs]e|\bOFL\b|openfontlicense\.org|scripts\.sil\.org\/OFL/i],
  ['Apache-2.0', /\bApache\s+(?:Licen[cs]e|2\.0)|apache\.org\/licenses/i],
  ['MIT', /\bMIT\b/],
  ['ISC', /\bISC\b/],
  ['CC0-1.0', /\bCC0\b|creativecommons\.org\/publicdomain\/zero/i],
];

/** The allowed licences a file's own licence text names. */
export const licencesNamedIn = (text) => NAMED.filter(([, re]) => re.test(String(text ?? ''))).map(([id]) => id);

/** Why a file's own licence text contradicts `licence`, or null when it does not: it states
 *  terms no allowed licence has, or it names licences of which `licence` is none. */
export function contradiction(text, licence) {
  if (!text) return null;
  for (const [re, what] of FORBIDDEN) if (re.test(text)) return `the file's own licence text states ${what}`;
  const named = licencesNamedIn(text);
  const claimed = String(licence).split(/\s+(?:AND|OR)\s+/);
  if (named.length && !named.some((id) => claimed.includes(id))) return `the file's own licence text names ${named.join(' and ')}, not ${licence}`;
  return null;
}

/** The words each licence's text holds, so a notice file can be checked to be the right text. */
export const NOTICE_MARKS = {
  'OFL-1.1': /SIL OPEN FONT LICENSE/i,
  'Apache-2.0': /Apache License/i,
  MIT: /Permission is hereby granted, free of charge/i,
  ISC: /Permission to use, copy, modify, and\/or distribute/i,
  'CC0-1.0': /CC0|Creative Commons Zero|No Copyright/i,
};
