/*
  Writes apps/<id>/LICENSE.md for every generator app.

    node scripts/licenses.mjs          # write them all
    node scripts/licenses.mjs --check  # fail if any is missing or out of date
    pnpm gen:licenses
    pnpm check:licenses

  Why generated rather than nine hand-written files: the licence text quotes a price and
  a sign-up URL, and invariant #4 says those live in `config/brand.ts` and nowhere else.
  A markdown file cannot import brand, so this reads brand and writes the markdown. The
  two files that existed before this script hardcoded "$15/month" and the MakerWorld
  link, and had already drifted apart from each other — the keycap one never got the
  commercial section the clicker one grew.

  The commercial half is a restatement of the MakerWorld membership terms, so that a
  person reading a repo file and a person reading the membership page are agreeing to the
  same thing. The membership page stays authoritative and says so in the text: these are
  nine copies, and nine copies drift.

  `licenseMarkdown()` is exported so `new-generator.mjs` can write a correct LICENSE.md
  for a new app at scaffold time, instead of copying the template's and leaving another
  app's name in a legal document.
*/

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

/** Apps that are not generators: the hub is the site itself, kit-demo is the component
 *  gallery. Neither produces a design anyone could sell. */
const NOT_GENERATORS = new Set(['hub', 'kit-demo']);

/** Fixed, not `new Date()`. Regenerating in a later year should not silently rewrite the
 *  copyright line on every app — that is a decision, not a side effect of running a script. */
const YEAR = 2026;

// ────────────────────────────────── brand ──────────────────────────────────

/** `config/brand.ts` is a plain object literal behind `as const`. Rather than pull a TS
 *  toolchain into a script that needs two strings out of it, lift the literal and
 *  evaluate it — and assert on the way out, so a change to brand's SHAPE fails loudly
 *  here instead of quietly writing a licence with `undefined/month` in it. */
export function readBrand() {
  const src = readFileSync(join(ROOT, 'config', 'brand.ts'), 'utf8');
  const start = src.indexOf('export const BRAND = ');
  const end = src.indexOf('} as const;', start);
  if (start < 0 || end < 0) throw new Error('config/brand.ts: cannot find `export const BRAND = { … } as const;`');

  const literal = src.slice(start + 'export const BRAND = '.length, end + 1);
  const brand = new Function(`return (${literal});`)();

  const price = brand?.pricing?.subscription;
  const url = brand?.urls?.mwCommercial;
  if (!price?.month || !price?.quarter || !price?.year || !price?.covers) {
    throw new Error('config/brand.ts: pricing.subscription is missing month/quarter/year/covers');
  }
  if (!url || String(url).startsWith('TODO')) {
    throw new Error(`config/brand.ts: urls.mwCommercial is not set (got ${url})`);
  }
  return brand;
}

// ────────────────────────────────── text ──────────────────────────────────

const money = (n) => `$${n}`;

/**
 * The licence every generator ships.
 *
 * Two tiers, one document. Personal use is CC BY-NC-ND 4.0, which is the free tier of
 * invariant #1 stated where a court would look: free is genuinely free, and the only
 * thing you cannot do without paying is sell what you make. The commercial half
 * restates the MakerWorld membership terms so the two agree.
 *
 * The third-party section is deliberately OUTSIDE both tiers. What a user uploads — a
 * logo, a font, a character, a brand name — is their problem on the free tier exactly as
 * much as on the paid one, and a clause that only appeared under "Commercial Use" would
 * read as though the free tier came with permission it cannot grant.
 */
export function licenseMarkdown({ title }) {
  const { pricing, urls } = readBrand();
  const s = pricing.subscription;

  return `<!-- Generated by scripts/licenses.mjs from config/brand.ts. Do not edit by hand:
     run \`pnpm gen:licenses\` after changing the price or the sign-up URL in brand. -->

# License — ${title}

Copyright (c) ${YEAR} Vostok Labs

Two licenses cover this generator and the designs it produces. **Personal use** is free,
under the Creative Commons license below. **Selling** what you make requires the
commercial license membership, which replaces the NonCommercial restriction for as long
as it is active.

---

## Personal use — CC BY-NC-ND 4.0

This work — the ${title} and the designs it produces — is licensed under the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.

You are free to:
- **Share** — copy and redistribute the material in any medium or format
- **Make** — 3D print or cut the generated designs, and use what you make, for your own personal, non-commercial purposes

Under the following terms:
- **Attribution** — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
- **NonCommercial** — You may not use the material for commercial purposes.
- **NoDerivatives** — If you remix, transform, or build upon the material, you may not distribute the modified material.

No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

To view a full copy of the underlying Creative Commons license, visit
https://creativecommons.org/licenses/by-nc-nd/4.0/

---

## Selling what you make — commercial license membership

An active subscription grants you a **non-exclusive license to manufacture and sell
physical 3D prints** of all eligible Vostok Labs models — including the designs you
generate with this tool — for the duration of your subscription period. An active
subscription is required to commercially manufacture, advertise, and sell physical prints
covered by this license.

It is **${money(s.month)}/month** (or ${money(s.quarter)}/quarter, ${money(s.year)}/year), and it covers ${s.covers}.

Get the commercial license here:
**${urls.mwCommercial}**

### What you can do

- Sell unlimited physical 3D prints of licensed models.
- Sell through Etsy, eBay, Amazon Handmade, Shopify, local markets, craft fairs, retail stores, and your own website.
- Print in any size, material, color, or print settings.
- Use the official product photos, renders, and marketing images in your listings.
- Use the official product descriptions as a starting point, or adapt them to your needs.
- Make minor functional modifications for printing or customer-specific customization, provided they do not create a new digital product for distribution or sale.

### Restrictions

- You may not share, redistribute, sell, or upload the digital model files, or any modified versions of them.
- You may not publish, sell, or distribute modified versions of the digital models.
- You may not create molds, castings, injection-molded products, or other forms of mass production without prior written permission.
- You may not use the designs in crowdfunding campaigns — Kickstarter or any other — without prior written permission.

---

## Third-party content, and your responsibility

This license covers Vostok Labs' own models and, where a model is customizable or
generated, the output you create with it. It says nothing about the content you put into
it.

- You are solely responsible for any text, logo, brand name, character, artwork, trademark, or other material you add to a model or use in your listings. Getting permission from its owner is your responsibility, not ours.
- This license grants no rights of any kind in third-party intellectual property. Nothing in it can be read as permission to reproduce someone else's IP.
- Vostok Labs does not review, approve, or endorse what you make or sell, and is not responsible or liable for it.
- You agree to indemnify and hold Vostok Labs harmless against any claim, demand, cost, or damages arising from the content you supply, or from the prints you make and sell.

---

## Notes

This license applies only to original Vostok Labs models and the output of this
generator. It does not extend to remixes or third-party models unless explicitly stated.
It is non-transferable and may not be sublicensed.

The commercial membership page is the authoritative statement of the current commercial
terms; where this file and that page differ, that page governs.
`;
}

// ────────────────────────────────── apps ──────────────────────────────────

/** The app's own page title, minus the site suffix — so the licence names the thing the
 *  user actually used. Falls back to the directory name. */
export function appTitle(appDir) {
  const indexPath = join(appDir, 'index.html');
  if (!existsSync(indexPath)) return basename(appDir);
  const m = readFileSync(indexPath, 'utf8').match(/<title>([^<]*)<\/title>/i);
  if (!m) return basename(appDir);
  return m[1].split(/\s+[·|-]\s+/)[0].trim() || basename(appDir);
}

export function generatorApps() {
  const appsDir = join(ROOT, 'apps');
  return readdirSync(appsDir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !NOT_GENERATORS.has(e.name))
    .filter((e) => existsSync(join(appsDir, e.name, 'index.html')))
    .map((e) => e.name);
}

function main() {
  const check = process.argv.includes('--check');
  const rows = [];
  const stale = [];

  for (const id of generatorApps()) {
    const appDir = join(ROOT, 'apps', id);
    const path = join(appDir, 'LICENSE.md');
    const title = appTitle(appDir);
    const wanted = licenseMarkdown({ title });
    const current = existsSync(path) ? readFileSync(path, 'utf8') : null;

    if (check) {
      const state = current === null ? 'MISSING' : current === wanted ? 'ok' : 'OUT OF DATE';
      if (state !== 'ok') stale.push(`apps/${id}/LICENSE.md — ${state}`);
      rows.push(`  ${state.padEnd(11)} apps/${id}/LICENSE.md`);
      continue;
    }

    writeFileSync(path, wanted, 'utf8');
    rows.push(`  apps/${id}/LICENSE.md`.padEnd(46) + title);
  }

  console.log(rows.join('\n'));

  if (check) {
    if (stale.length) {
      console.error(`\n${stale.length} licence file(s) need regenerating. Run: pnpm gen:licenses`);
      process.exit(1);
    }
    console.log(`\nLicence check passed: all ${rows.length} generator apps carry a current LICENSE.md.`);
    return;
  }
  console.log(`\nWrote ${rows.length} licence files.`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
